---
authors:
  - Jeff Groom
dependencies:
  ansible.netcommon: '>=1.0.0'
license_file: LICENSE
version: 0.0.1
name: saos6
namespace: ciena
readme: README.md
repository: https://github.com/ciena/ciena.saos6
tags: [ciena, saos, networking, ethernet]
